# Generated by Django 3.1 on 2021-07-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210624_0959'),
        ('carts', '0003_auto_20210623_2341'),
    ]

    operations = [
    ]
