# Generated by Django 3.1 on 2021-07-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210605_0928'),
        ('category', '0002_auto_20210604_1319'),
    ]

    operations = [
    ]
